version: "3.9"

services:
  app:
    build: .
    container_name: link_shortener_app
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: redis:7
    container_name: link_shortener_redis
    ports:
      - "6379:6379"